# Generated by Django 4.2.8 on 2023-12-09 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="Название кофейни")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True, verbose_name="Описание кофейни"),
                ),
                ("rating", models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name="Рейтинг 2Gis")),
                ("address", models.CharField(max_length=100, verbose_name="Адрес кофейни")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="establishment/images/poster",
                        verbose_name="Постер кофейни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кофейня",
                "verbose_name_plural": "Кофейни",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название города")),
                ("slug", models.SlugField(max_length=200, verbose_name="Ссылка на город")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=11, verbose_name="Номер телефона")),
                ("website", models.URLField(verbose_name="Вебсайт")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название района")),
                ("slug", models.SlugField(max_length=200, verbose_name="Ссылка на район")),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
            },
        ),
        migrations.CreateModel(
            name="ImageCafe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_file", models.ImageField(upload_to="images")),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Ширина")),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "Координаты",
                "verbose_name_plural": "Координаты",
            },
        ),
        migrations.CreateModel(
            name="StopFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Название")),
                ("tag", models.SlugField(max_length=200, unique=True, verbose_name="Уникальный Тег")),
            ],
            options={
                "verbose_name": "Доп. свойство",
                "verbose_name_plural": "Доп. свойства",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=100, verbose_name="День недели")),
                ("day_off", models.BooleanField(default=False, verbose_name="Выходной")),
                ("start", models.CharField(blank=True, max_length=145, null=True, verbose_name="Начало работы")),
                ("end", models.CharField(blank=True, max_length=145, null=True, verbose_name="Конец работы")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="worked", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Время работы",
                "verbose_name_plural": "Время работы",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="favorite", to="cafe.cafe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="cafe",
            name="cities",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.contact",
                verbose_name="Контакты",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.district",
                verbose_name="Район",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cafe",
                to="cafe.point",
                verbose_name="Координаты",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="stop_factors",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.stopfactor",
                verbose_name="Доп. свойства",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(fields=("user", "cafe"), name="uniquefavorite"),
        ),
    ]
