# Generated by Django 4.2.8 on 2024-01-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="Название кофейни")),
                (
                    "description",
                    models.TextField(blank=True, max_length=1500, null=True, verbose_name="Описание кофейни"),
                ),
                ("district", models.CharField(max_length=100, verbose_name="Район")),
                ("address", models.CharField(max_length=100, verbose_name="Адрес кофейни")),
                ("latitude", models.FloatField(blank=True, null=True, verbose_name="Широта")),
                ("longitude", models.FloatField(blank=True, null=True, verbose_name="Долгота")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="establishment/images/poster",
                        verbose_name="Постер кофейни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кофейня",
                "verbose_name_plural": "Кофейни",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="тэг")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tag", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэг",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(max_length=150, verbose_name="Время работы")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="worked", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Время работы",
                "verbose_name_plural": "Время работы",
            },
        ),
        migrations.CreateModel(
            name="Roaster",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Обжарщик кофе")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="roaster", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обжарщик кофе",
                "verbose_name_plural": "Обжарщик кофе",
            },
        ),
        migrations.CreateModel(
            name="ImageCafe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_file", models.ImageField(blank=True, upload_to="images")),
                ("image_url", models.URLField(blank=True)),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="image", to="cafe.cafe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Фильтр")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="filter", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильтр",
                "verbose_name_plural": "Фильтр",
            },
        ),
        migrations.CreateModel(
            name="Drink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="напиток")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="drink", to="cafe.cafe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Напиток",
                "verbose_name_plural": "Напиток",
            },
        ),
        migrations.CreateModel(
            name="Alternative",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Альтернатива")),
                (
                    "cafe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative",
                        to="cafe.cafe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Альтернатива",
                "verbose_name_plural": "Альтернатива",
            },
        ),
    ]
