# Generated by Django 4.2.8 on 2023-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='stop_factors',
        ),
        migrations.AddField(
            model_name='cafe',
            name='stop_factors',
            field=models.ManyToManyField(null=True, related_name='cafe', to='cafe.stopfactor', verbose_name='Доп. свойства'),
        ),
    ]
