# Generated by Django 4.2.8 on 2023-12-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cafe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="cities",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.contact",
                verbose_name="Контакты",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="district",
            field=models.ManyToManyField(blank=True, related_name="cafe", to="cafe.district", verbose_name="Район"),
        ),
        migrations.AddField(
            model_name="cafe",
            name="metro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.metro",
                verbose_name="Метро",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="point",
            field=models.ManyToManyField(blank=True, related_name="cafe", to="cafe.point", verbose_name="Координаты"),
        ),
        migrations.AddField(
            model_name="cafe",
            name="stop_factors",
            field=models.ManyToManyField(
                blank=True, related_name="cafes", to="cafe.stopfactor", verbose_name="Доп. свойства"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(fields=("user", "cafe"), name="uniquefavorite"),
        ),
    ]
