# Generated by Django 4.2.8 on 2023-12-10 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Цвет должен быть в формате #123456", regex="^#[0-9a-fA-F]{6}$"
                            )
                        ],
                        verbose_name="Цвет ветки метро",
                    ),
                ),
                ("comment", models.CharField(max_length=200, verbose_name="Название ветки метро")),
                ("distance", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Расстояние до станции")),
                ("name", models.CharField(max_length=100, verbose_name="Название станции метро")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="Ссылка на метро")),
            ],
            options={
                "verbose_name": "Станция",
                "verbose_name_plural": "Станции",
            },
        ),
        migrations.AddField(
            model_name="cafe",
            name="metro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cafe",
                to="cafe.metro",
                verbose_name="Метро",
            ),
        ),
    ]
