# Generated by Django 4.2.8 on 2024-01-19 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cafe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="roaster",
            field=models.ManyToManyField(max_length=100, to="cafe.roaster", verbose_name="Обжарщик кофе"),
        ),
        migrations.AddField(
            model_name="cafe",
            name="scheduleincafe",
            field=models.ManyToManyField(
                max_length=100, related_name="cafes", to="cafe.scheduleincafe", verbose_name="Время работы"
            ),
        ),
        migrations.AddField(
            model_name="cafe",
            name="tag",
            field=models.ManyToManyField(max_length=100, to="cafe.tag", verbose_name="Тэг"),
        ),
        migrations.AddField(
            model_name="address",
            name="cafe",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="address", to="cafe.cafe"
            ),
        ),
    ]
