# Generated by Django 4.2.8 on 2024-02-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название кофейни"),
        ),
    ]
