# Generated by Django 4.2.8 on 2023-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_remove_cafe_stop_factors_cafe_stop_factors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopfactor',
            old_name='tag',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='district',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='point',
        ),
        migrations.AddField(
            model_name='cafe',
            name='district',
            field=models.ManyToManyField(null=True, related_name='cafe', to='cafe.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='point',
            field=models.ManyToManyField(related_name='cafe', to='cafe.point', verbose_name='Координаты'),
        ),
    ]
