# Generated by Django 4.2.8 on 2024-01-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additional",
            options={"ordering": ("name",), "verbose_name": "Дополнение", "verbose_name_plural": "Дополнения"},
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("name",), "verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="drink",
            options={
                "ordering": ("cafe",),
                "verbose_name": "Стоимость напитка",
                "verbose_name_plural": "Стоимость напитка",
            },
        ),
        migrations.AlterModelOptions(
            name="drinkincafe",
            options={"ordering": ("name",), "verbose_name": "Напиток", "verbose_name_plural": "Напитки"},
        ),
        migrations.AlterModelOptions(
            name="imagecafe",
            options={"verbose_name": "Фото заведения", "verbose_name_plural": "Фото заведений"},
        ),
        migrations.AlterModelOptions(
            name="roaster",
            options={"ordering": ("name",), "verbose_name": "Обжарщик кофе", "verbose_name_plural": "Обжарщики Кофе"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",), "verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="additional",
            new_name="additionals",
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="drink",
            new_name="drinks",
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="roaster",
            new_name="roasters",
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="scheduleincafe",
            new_name="schedulesincafe",
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="tag",
            new_name="tags",
        ),
        migrations.RenameField(
            model_name="scheduleincafe",
            old_name="schedule",
            new_name="schedules",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="drinks",
        ),
        migrations.AddField(
            model_name="drink",
            name="drink",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drinks_in_cafe",
                to="cafe.drinkincafe",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="cafe",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="drink_in_cafe", to="cafe.cafe"
            ),
        ),
    ]
