# Generated by Django 4.2.8 on 2023-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_rename_tag_stopfactor_slug_remove_cafe_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='district',
            field=models.ManyToManyField(blank=True, related_name='cafe', to='cafe.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='point',
            field=models.ManyToManyField(blank=True, related_name='cafe', to='cafe.point', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='stop_factors',
            field=models.ManyToManyField(blank=True, related_name='cafes', to='cafe.stopfactor', verbose_name='Доп. свойства'),
        ),
    ]
