# Generated by Django 4.2.8 on 2024-02-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0003_remove_address_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkincafe",
            name="cafe",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="drink_in_cafe", to="cafe.cafe"
            ),
        ),
        migrations.AlterField(
            model_name="drinkincafe",
            name="drink",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="drink_in_cafe", to="cafe.drink"
            ),
        ),
    ]
