# Generated by Django 4.2.8 on 2024-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0003_alter_additional_options_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Адрес кофейни"),
        ),
    ]
