# Generated by Django 4.2.8 on 2023-12-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_cafe_district_alter_cafe_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longitude',
            field=models.FloatField(blank=True, max_length=200, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='imagecafe',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagecafe',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
