# Generated by Django 4.2.8 on 2023-12-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_cafe_latitude_cafe_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='longitude',
        ),
    ]
