# Generated by Django 4.2.8 on 2023-12-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_remove_cafe_latitude_remove_cafe_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ('name',), 'verbose_name': 'Кофейня', 'verbose_name_plural': 'Кофейни'},
        ),
    ]
