# Generated by Django 4.2.8 on 2023-12-15 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0002_metro_cafe_metro"),
        ("cafe", "0007_alter_cafe_options"),
    ]

    operations = []
