# Generated by Django 4.2.8 on 2023-12-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0008_merge_0002_metro_cafe_metro_0007_alter_cafe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stopfactor",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
